[Variables]
; HWInfo_GPU variables

TempUnit=°C

HWiNFOSensorId0=0xe0002000
HWiNFOSensorInstance0=0x0
HWiNFOType0=SensorName

HWInfoDesc1=GPU Temp
HWiNFOSensorId1=0xe0002000
HWiNFOSensorInstance1=0x0
HWiNFOEntryId1=0x1000000
HWiNFOType1=CurrentValue
HWInfoValue1=%1#TempUnit#
HWInfoMin1=25
HWInfoMax1=90

HWInfoDesc2=GPU Fan
HWiNFOSensorId2=0xe0002000
HWiNFOSensorInstance2=0x0
HWiNFOEntryId2=0x3000000
HWiNFOType2=CurrentValue
HWInfoValue2=%1 RPM
HWInfoMin2=0
HWInfoMax2=2000

HWInfoDesc3=GPU Clock
HWiNFOSensorId3=0xe0002000
HWiNFOSensorInstance3=0x0
HWiNFOEntryId3=0x6000000
HWiNFOType3=CurrentValue
HWInfoValue3=%1 Mhz
HWInfoMin3=0
HWInfoMax3=1950

HWInfoDesc4=GPU Usage
HWiNFOSensorId4=0xe0002000
HWiNFOSensorInstance4=0x0
HWiNFOEntryId4=0x7000000
HWiNFOType4=CurrentValue
HWInfoValue4=%1 %
HWInfoMin4=0
HWInfoMax4=100

HWInfoDesc5=GPU D3D Usage
HWiNFOSensorId5=0xe0002000
HWiNFOSensorInstance5=0x0
HWiNFOEntryId5=0x7000009
HWiNFOType5=CurrentValue
HWInfoValue5=%1 %
HWInfoMin5=0
HWInfoMax5=100

HWInfoDesc6=GPU Memory
HWiNFOSensorId6=0xe0002000
HWiNFOSensorInstance6=0x0
HWiNFOEntryId6=0x80000fc
HWiNFOType6=CurrentValue
HWInfoValue6=%1 MB
HWInfoMin6=0
HWInfoMax6=6144

HWInfoDesc7=GPU Memory Usage
HWiNFOSensorId7=0xe0002000
HWiNFOSensorInstance7=0x0
HWiNFOEntryId7=0x7000008
HWiNFOType7=CurrentValue
HWInfoValue7=%1 %
HWInfoMin7=0
HWInfoMax7=100

HWInfoDesc8=CPU Temp
HWiNFOSensorId8=0xf7006687
HWiNFOSensorInstance8=0x0
HWiNFOEntryId8=0x1000000
HWiNFOType8=CurrentValue
HWInfoValue8=%1#TempUnit#
HWInfoMin8=00
HWInfoMax8=100

HWInfoDesc9=Mobo Temp
HWiNFOSensorId9=0xf7006687
HWiNFOSensorInstance9=0x0
HWiNFOEntryId9=0x1000001
HWiNFOType9=CurrentValue
HWInfoValue9=%1#TempUnit#
HWInfoMin9=00
HWInfoMax9=100

HWInfoDesc10=CPU Usage
HWiNFOSensorId10=0xf0000300
HWiNFOSensorInstance10=0x0
HWiNFOEntryId10=0x7000023
HWiNFOType10=CurrentValue
HWInfoValue10=%1 %
HWInfoMin10=0
HWInfoMax10=100


